version: 2
jobs:
  build:
    working_directory: ~/edustor-pdfgen
    docker:
      - image: docker:git
    environment:
      IMAGE_NAME: quay.io/edustor/pdfgen
      SWARM_CA_URL: https://wutiarn.keybase.pub/swarm/ca.pem
      SWARM_CERT_URL: https://wutiarn.keybase.pub/swarm/cert.pem
    steps:
      - checkout
      - restore_cache:
          key: edustor-pdfgen-{{ .Revision }}
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker login -u="edustor+gitlabci" -p="$REGISTRY_PASSWORD" quay.io
            docker build -t $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM -f ci.Dockerfile .
            docker tag $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM $IMAGE_NAME:latest
      - run:
          name: Push docker image
          command: |
            docker push $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push $IMAGE_NAME:latest
            fi
#      - run:
#          name: Deploy to swarm
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              mkdir -p /root/.docker
#              curl -sSL $SWARM_CA_URL > /root/.docker/ca.pem
#              curl -sSL $SWARM_CERT_URL > /root/.docker/cert.pem
#              echo ${SWARM_KEY} | base64 -d > /root/.docker/key.pem
#              export DOCKER_HOST=swarm.wutiarn.ru:2376
#              export DOCKER_TLS_VERIFY=1
#              docker --tlsverify --tlscacert /root/.docker/ca.pem \
#                --tlscert /root/.docker/cert.pem --tlskey /root/.docker/key.pem \
#                service update --with-registry-auth --image $IMAGE_NAME:ci-$CIRCLE_BUILD_NUM sw0_edustor-pdfgen
#            fi